/************************************************************
** 文件名：MRReturnCode.h
** Copyright (c) 2011-2012 中国船舶工业系统工程研究院
** 创建人：杨猛<635584332@qq.com>
** 日  期：2011-07-26
** 修改人：无
** 日  期：无
** 描  述：MRReturnCode头文件
** 版  本：Version 0.1
**----------------------------------------------------------
************************************************************/

#ifndef MRRETURNCODE_H
#define MRRETURNCODE_H
#include "ReturnCode.h"
typedef long _RETURNCODE_T;
const _RETURNCODE_T RETURNCODE_ERROR = -1;
const _RETURNCODE_T RETURNCODE_MONITORAGENT_INIT_FAILED = 180;
const _RETURNCODE_T RETURNCODE_MONITORAGENT_COMPSINFO_FULL = 181;
const _RETURNCODE_T RETURNCODE_MONITORAGENT_DELETEINSTENCE_FAILED = 182;
const _RETURNCODE_T RETURNCODE_TOPICPUBMNG_INIT_FAILED = 183;
const _RETURNCODE_T RETURNCODE_COMPSPUBMNG_INIT_FAILED =184;
const _RETURNCODE_T RETURNCODE_NODEPUBMNG_INIT_FAILED =185;
const _RETURNCODE_T RETURNCODE_MONITORINFOPROCESSOR_INIT_FAILED = 186;
const _RETURNCODE_T RETURNCODE_HANDLEDATASTREAMINFOFUN_ERROR = 187;
const _RETURNCODE_T RETURNCODE_MONITOR_TOPICINFOGET_FAILED = 188;
const _RETURNCODE_T RETURNCODE_MONITOR_NODEFIXEDINFOGET_FAILED = 189;
const _RETURNCODE_T RETURNCODE_MONITOR_NODEREALTIMEINFOGET_FAILED = 190;
const _RETURNCODE_T RETURNCODE_MONITOR_COMPINFOGET_FAILED = 200;
const _RETURNCODE_T RETURNCODE_NODEQRYREQUEST_ERROR=201;
const _RETURNCODE_T RETURNCODE_INVALIDPARAMETER=202;
const _RETURNCODE_T RETURNCODE_MONITORCLIENT_CREATE_FAILED= 203;
const _RETURNCODE_T	RETURNCODE_MONITORSERVER_CREATE_FAILED= 204;
const _RETURNCODE_T RETURNCODE_REGISTERCOMPONENT_FAILED= 205;
const _RETURNCODE_T RETURNCODE_DATAWRITER_ERROR= 206;

const _RETURNCODE_T RETURNCODE_NO_MEMORY_RECORD=216;
const _RETURNCODE_T RETURNCODE_SENDRECORD_FAILED=217;
const _RETURNCODE_T RETURNCODE_RECORDCLIENT_NOT_EXIST=218;
const _RETURNCODE_T RETURNCODE_RECORDSERVER_CREATE_FAILED=219;

const _RETURNCODE_T RETURNCODE_MR_COMMUNICATION_ERROR = 300;
const _RETURNCODE_T RETURNCODE_MR_NOINFO_ERROR = 301;

#endif
